name: Create and Test Conda Environment

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create or update conda environment
      run: |
        if conda info --envs | grep -q "myenv"; then
          echo "Environment 'myenv' already exists. Removing and recreating."
          conda env remove --name myenv
        fi
        conda create --name myenv python=3.8 -y

    - name: Activate conda environment
      run: |
        conda init bash
        source ~/.bashrc
        conda activate myenv

    - name: Print Hello World
      run: |
        python -c "print('Hello, World!')"

    - name: Install requirements
        run: |
        python install.py
