name: Create and Test Conda Environment

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Demo test
      run: |
        if conda info --envs | grep -q "myenv"; then
          echo "Environment 'myenv' already exists. Skipping creation."
        else
          echo "Environment 'myenv' does not exist. Creating."
          conda create --name myenv python=3.8 -y
        fi
        conda init bash
        source ~/.bashrc
        conda activate myenv
        which python
        python -c "print('Hello, World!')"
        pip install pytest
        pip install pytest-html
        pytest test/test_cellbin_pipeline.py -v




#    - name: Install requirements
#      run: |
#        python install.py
#    - name: Run pytest
#      run: |
#        python test/test_cellbin_pipeline.py
